def cargar_crudos(ruta):            ...
def normalizar_fechas(df):          ...
def separar_devoluciones(df):       ...
def limpiar_clientes(df):           ...
def deduplicar_clientes(df):        ...
def limpiar_productos(df):          ...
def marcar_huerfanos(ventas, cli, prod): ...
def main():                         ...

DESCARTES = []

def descartar(df, motivo, origen):
    """Registra filas eliminadas antes de sacarlas del flujo."""
    if len(df):
        d = df.copy()
        d["motivo_descarte"] = motivo
        d["archivo_origen"] = origen
        DESCARTES.append(d)
        